local Credentials = require("goodreadskosync.auth.credentials")
local Storage = require("goodreadskosync.storage")

describe("auth.credentials", function()
    it("saves and loads credentials", function()
        Storage.reset()
        assert_false(Credentials.has())
        assert_true(Credentials.save("me@example.com", "secret"))
        assert_true(Credentials.has())
        local loaded = Credentials.load()
        assert_equal("me@example.com", loaded.email)
        assert_equal("secret", loaded.password)
    end)

    it("rejects empty values", function()
        Storage.reset()
        assert_false(Credentials.save("", "secret"))
        assert_false(Credentials.save("me@example.com", ""))
    end)

    it("clears saved credentials", function()
        Storage.reset()
        Credentials.save("me@example.com", "secret")
        Credentials.clear()
        assert_false(Credentials.has())
        assert_nil(Credentials.load())
    end)
end)
