local Epub = require("goodreadskosync.resolver.epub")
local fixtures = require("fixtures.opf")

describe("resolver.epub", function()
    it("parses title, author, ISBN, publisher, language and date", function()
        local md = Epub.parseOpf(fixtures.clean)
        assert_equal("Sapiens", md.title)
        assert_equal(1, #md.authors)
        assert_equal("Yuval Noah Harari", md.authors[1])
        assert_equal("9780062316097", md.isbn13)
        assert_equal("Harper", md.publisher)
        assert_equal("en", md.language)
        assert_equal(2015, md.publication_year)
        assert_equal("Sapiens", md.series)
        assert_equal("1", md.series_index)
    end)

    it("parses ISBN-10 identifiers", function()
        local md = Epub.parseOpf(fixtures.isbn10)
        assert_equal("0306406152", md.isbn10)
        -- Conversion to ISBN-13 is done by resolver.identifiers, not the raw parser.
        assert_nil(md.isbn13)
    end)

    it("parses ASIN identifiers", function()
        local md = Epub.parseOpf(fixtures.asin)
        assert_equal("B00J8QK4CE", md.asin)
    end)

    it("parses explicit Goodreads identifiers", function()
        local md = Epub.parseOpf(fixtures.goodreads)
        assert_equal("23692271", md.goodreads_id)
    end)

    it("separates contributors from primary authors", function()
        local md = Epub.parseOpf(fixtures.multiple)
        assert_equal(1, #md.authors)
        assert_equal("A One", md.authors[1])
        assert_equal(1, #md.contributors)
        assert_equal("B Two", md.contributors[1].name)
    end)

    it("collects multiple identifier types at once", function()
        local md = Epub.parseOpf(fixtures.multiple)
        assert_equal("9780306406157", md.isbn13)
        assert_equal("B00J8QK4CE", md.asin)
        assert_equal("99", md.goodreads_id)
    end)

    it("returns no identifiers for a bare document", function()
        local md = Epub.parseOpf(fixtures.none)
        assert_equal("No Identifiers", md.title)
        assert_nil(md.isbn13)
        assert_nil(md.asin)
        assert_nil(md.goodreads_id)
    end)

    it("does not crash on malformed XML", function()
        local md = Epub.parseOpf(fixtures.malformed)
        assert_equal("Broken", md.title)
        assert_nil(md.isbn13)
    end)

    it("does not treat a subtitle as a title element", function()
        local md = Epub.parseOpf(
            "<metadata><dc:subtitle>Sub</dc:subtitle><dc:title>Real</dc:title></metadata>")
        assert_equal("Real", md.title)
    end)

    it("extracts the rootfile path from a container", function()
        assert_equal("OEBPS/content.opf", Epub.rootfilePath(fixtures.container))
    end)

    it("handles a missing container gracefully", function()
        assert_nil(Epub.rootfilePath(nil))
    end)
end)
