local ToastGlyphs = require("goodreadskosync.toast_glyphs")

describe("toast_glyphs", function()
    it("defaults to monochrome symbols", function()
        ToastGlyphs.setStyle("symbols")
        assert_equal("symbols", ToastGlyphs.getStyle())
        assert_equal("✓", ToastGlyphs.forKind("success"))
        assert_equal("★", ToastGlyphs.forKind("star"))
    end)

    it("returns no glyph when disabled", function()
        ToastGlyphs.setStyle("none")
        assert_equal("", ToastGlyphs.forKind("success"))
        ToastGlyphs.setStyle("symbols")
    end)

    it("maps banner kinds to KOReader icons", function()
        assert_equal("check", ToastGlyphs.icon("success"))
        assert_equal("notice-warning", ToastGlyphs.icon("warn"))
        assert_equal("notice-info", ToastGlyphs.icon("unknown"))
    end)

    it("ignores an unknown or removed style", function()
        ToastGlyphs.setStyle("symbols")
        assert_false(ToastGlyphs.setStyle("bogus"))
        assert_false(ToastGlyphs.setStyle("emoji"))
        assert_equal("symbols", ToastGlyphs.getStyle())
    end)
end)
